### ISSUE TITLE
IndexError: index 5 is out of bounds for axis 0 with size 4

### ISSUE THREAD

**Issue by myseverus** [whatamazing1/DEAttentionDTA#2]
Traceback (most recent call last):
  File "C:/Users/20825/Desktop/bioinformations/DEAttentionDTA-main1/src/main.py", line 45, in <module>
    train_dataset = MyDataset('core2013',data_path, max_seq_len, max_smi_len)
  File "C:\Users\20825\Desktop\bioinformations\DEAttentionDTA-main1\src\Dataset.py", line 72, in __init__
    position[row[1]] = eval(row[5])
  File "C:\anaconda\envs\train\lib\site-packages\pandas\core\series.py", line 978, in __getitem__
    return self._values[key]
IndexError: index 5 is out of bounds for axis 0 with size 4
Hello, author, this error occurs when I run core2013 file, how should I solve it, thank you very much

**Comment by whatamazing1** [comment]
core2013 don't have the position attribute，and there is no position data in its data table，if you want to get the inference result of core2013, you can choose to run src-v2/main.py, v2 don't need the position。

**Comment by whatamazing1** [comment]
https://academic.oup.com/bioinformatics/article/40/6/btae319/7696315  
I explained in detail the differences between v1 and v2 in my article。
